### ISSUE TITLE
Access to old documentation

### ISSUE THREAD

**Issue by TorzuoliH** [angular/material.angular.io#412]
Hello!

When using AngularJS Material, it was possible to navigate between each documentation version (still possible).

I'm a user of `angular/material2` in an older version than the one which is referenced. Is there somewhere I can find documentation about version like `2.0.0-beta.XXX`? I can't find what I'm searching for with old __md__ prefixes (now __mat__).

Thanks!

**Comment by willshowell** [comment]
A version picker should be available soon: https://github.com/angular/material.angular.io/pull/406

That won't help much for beta docs though. Since the docs site is built of documentation in the source, your best bet is to select the version tag you're using and explore the source. The examples and markdown docs will be available there as well.

**2.0.0-beta.10**: https://github.com/angular/material2/tree/2.0.0-beta.10

If you really want to use the docs site: clone this repo, roll it back to the version you need, and run it locally.

**Comment by TorzuoliH** [comment]
Oh ok, I was searching versions in branches, not in tags... Thanks for your help @willshowell! 👍
