### ISSUE TITLE
Cannot find module '@angular/material-examples'

### ISSUE THREAD

**Issue by ElderJames** [angular/material.angular.io#452]
Getting a error during the build script running:

> Cannot find module '@angular/material-examples'

**Comment by qazq** [comment]
run tools/fetch-assets.sh

**Comment by sebinbenjamin** [comment]
I get other errors after doing this.

`/material.angular.io$ ng serve --open
Your global Angular CLI version (6.0.8) is greater than your local
version (6.0.1). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
** Angular Live Development Server is listening on localhost: 4200, open your browser on http://localhost:4200/ **

Date: 2018-06-16T05:41:01.172Z
Hash: 96ceff441dfd5e765a0f
Time: 24223ms
chunk {deeppurple-amber} deeppurple-amber.js (deeppurple-amber) 70.5 kB [initial] [rendered]
chunk {indigo-pink} indigo-pink.js (indigo-pink) 70.3 kB [initial] [rendered]
chunk {main} main.js (main) 1.94 kB [initial] [rendered]
chunk {pink-bluegrey} pink-bluegrey.js (pink-bluegrey) 72.4 kB [initial] [rendered]
chunk {purple-green} purple-green.js (purple-green) 72.4 kB [initial] [rendered]
chunk {runtime} runtime.js (runtime) 5.36 kB [entry] [rendered]
chunk {styles} styles.js (styles) 101 kB [initial] [rendered]
chunk {vendor} vendor.js (vendor) 325 kB [initial] [rendered]

ERROR in : Can't bind to 'sticky' since it isn't a known property of 'ng-container'.
1. If 'sticky' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("-table [dataSource]="dataSource" *ngFor="let table of tables"><ng-container matColumnDef="position" [ERROR ->][sticky]="isSticky(stickyColumns, 'position')"><mat-header-cell *matHeaderCellDef>Position</mat-heade")
: Can't bind to 'sticky' since it isn't a known property of 'ng-container'.
1. If 'sticky' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("*matFooterCellDef>Position Footer</mat-footer-cell></ng-container><ng-container matColumnDef="name" [ERROR ->][sticky]="isSticky(stickyColumns, 'name')"><mat-header-cell *matHeaderCellDef>Name</mat-header-cell><")
: Can't bind to 'stickyEnd' since it isn't a known property of 'ng-container'.
1. If 'stickyEnd' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("l *matFooterCellDef>Name Footer</mat-footer-cell></ng-container><ng-container matColumnDef="weight" [ERROR ->][stickyEnd]="isSticky(stickyColumns, 'weight')"><mat-header-cell *matHeaderCellDef>Weight</mat-header")
: Can't bind to 'stickyEnd' since it isn't a known property of 'ng-container'.
1. If 'stickyEnd' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("*matFooterCellDef>Weight Footer</mat-footer-cell></ng-container><ng-container matColumnDef="symbol" [ERROR ->][stickyEnd]="isSticky(stickyColumns, 'symbol')"><mat-header-cell *matHeaderCellDef>Symbol</mat-header")
: Can't bind to 'matHeaderRowDefSticky' since it isn't a known property of 'mat-header-row'.
1. If 'mat-header-row' is an Angular component and it has 'matHeaderRowDefSticky' input, then verify that it is part of this module.
2. If 'mat-header-row' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("at-footer-cell *matFooterCellDef>Filler footer cell</mat-footer-cell></ng-container><mat-header-row [ERROR ->]*matHeaderRowDef="displayedColumns; sticky: isSticky(stickyHeaders, 'header-1')"></mat-header-row><ma")
: Property binding matHeaderRowDefSticky not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("ell</mat-cell><mat-footer-cell *matFooterCellDef>Filler footer cell</mat-footer-cell></ng-container>[ERROR ->]<mat-header-row *matHeaderRowDef="displayedColumns; sticky: isSticky(stickyHeaders, 'header-1')"></ma")
: Can't bind to 'matHeaderRowDefSticky' since it isn't a known property of 'mat-header-row'.
1. If 'mat-header-row' is an Angular component and it has 'matHeaderRowDefSticky' input, then verify that it is part of this module.
2. If 'mat-header-row' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("ef="displayedColumns; sticky: isSticky(stickyHeaders, 'header-1')"></mat-header-row><mat-header-row [ERROR ->]*matHeaderRowDef="displayedColumns; sticky: isSticky(stickyHeaders, 'header-2')"></mat-header-row><ma")
: Property binding matHeaderRowDefSticky not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("w *matHeaderRowDef="displayedColumns; sticky: isSticky(stickyHeaders, 'header-1')"></mat-header-row>[ERROR ->]<mat-header-row *matHeaderRowDef="displayedColumns; sticky: isSticky(stickyHeaders, 'header-2')"></ma")
: Can't bind to 'matFooterRowDefSticky' since it isn't a known property of 'mat-footer-row'.
1. If 'mat-footer-row' is an Angular component and it has 'matFooterRowDefSticky' input, then verify that it is part of this module.
2. If 'mat-footer-row' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("/mat-header-row><mat-row *matRowDef="let row; columns: displayedColumns;"></mat-row><mat-footer-row [ERROR ->]*matFooterRowDef="displayedColumns; sticky: isSticky(stickyFooters, 'footer-1')"></mat-footer-row><ma")
: Property binding matFooterRowDefSticky not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". (", 'header-2')"></mat-header-row><mat-row *matRowDef="let row; columns: displayedColumns;"></mat-row>[ERROR ->]<mat-footer-row *matFooterRowDef="displayedColumns; sticky: isSticky(stickyFooters, 'footer-1')"></ma")
: Can't bind to 'matFooterRowDefSticky' since it isn't a known property of 'mat-footer-row'.
1. If 'mat-footer-row' is an Angular component and it has 'matFooterRowDefSticky' input, then verify that it is part of this module.
2. If 'mat-footer-row' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("ef="displayedColumns; sticky: isSticky(stickyFooters, 'footer-1')"></mat-footer-row><mat-footer-row [ERROR ->]*matFooterRowDef="displayedColumns; sticky: isSticky(stickyFooters, 'footer-2')"></mat-footer-row></m")
: Property binding matFooterRowDefSticky not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("w *matFooterRowDef="displayedColumns; sticky: isSticky(stickyFooters, 'footer-1')"></mat-footer-row>[ERROR ->]<mat-footer-row *matFooterRowDef="displayedColumns; sticky: isSticky(stickyFooters, 'footer-2')"></ma")

ℹ ｢wdm｣: Failed to compile.
^C`
