### ISSUE TITLE
infra: hardcoded paths break ability to host docs on-premise

### ISSUE THREAD

**Issue by umdstu** [angular/material.angular.io#623]
This repository is meant to be configurable and built to be self-deployed. It works, mostly, but there are issues:

1. Assets don't load - many of the components point to the assets found in assets/img, etc., but the instructions say to simply update material2-docs-content repo, however those files have the asset paths hardcoded again to material.angular.io/assets/ rather than a relative path.

2. VersionPicker- This ties into number 1. The versions.json file points directly to the material.angular.io host, not a relative asset path, so it doesn't load and the dropdown appears obviously broken in the UI. 

3. Material Icons fonts and css loaded via google-fonts, directly in the index.html. Could be made more configurable to point to a self-hosted version of the fonts w/o modifying the index.html page.

**Comment by Splaktar** [comment]
I've updated the link to `versions.json` in `version-picker.ts` to use a relative URL. PR coming soon.

If you want to deploy your own version of the docs site, you will need to update 
- [assets/versions.json](https://github.com/angular/material.angular.io/blob/e62a8ab2fda49a2f810ded27be170cd27c692bb2/src/assets/versions.json) to use your URLs

If you want to deploy behind a firewall, you will need to do one of these:
- Get your IT admin to open access to the CDNs used for the fonts and HammerJS
- Update [index.html](https://github.com/angular/material.angular.io/blob/master/src/index.html) to reference local resources instead of the CDN
  - HammerJS is already installed locally
    - In `main.ts`: `import 'hammerjs';`
  - You would need to install `material-design-icons` as a dependency
     - Then copy the appropriate files to `assets/material-design-icons`
     - In `styles.scss`: `@import './assets/material-design-icons/material-icons';`
  - Download the Roboto fonts from [here](https://fonts.google.com/specimen/Roboto+Mono?selection.family=Roboto+Mono:300|Roboto:300,400,500,700) and add those to `assets/`

**Comment by umdstu** [comment]
@Splaktar Awesome, thanks for the great/quick work on this. I will give it another go building/standing this up internally!
